name: Playwright Tests

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

  # schedule:
  #   - cron: '10 16 * * *'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run tests and generate Allure report
      - name: Run tests and generate Allure report
        run: npx allure run -- npx playwright test api-tests/TC01_Booking.spec.js

      # Post summary to Pull Request
      - name: Run Allure GitHub Action
        uses: allure-framework/allure-report@v0
        with:
          report-directory: "./allure-report"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Upload report as artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-report
          retention-days: 30